# Generated by Django 2.2.6 on 2019-10-07 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='collectionpoints',
            name='materials',
            field=models.CharField(default=1, max_length=255, verbose_name='Materiais Recolhidos'),
            preserve_default=False,
        ),
    ]
